packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.9
  '@types/node': ^25.0.2
  lefthook: ^2.0.12
  tsx: ^4.21.0
  turbo: ^2.6.3
  typescript: ^5.9.3
  vite-tsconfig-paths: ^6.0.1
  vitest: ^4.0.15

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - lefthook
  - msw
  - protobufjs
  - sharp
  - unrs-resolver
