packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.10
  '@types/node': ^24.10.4
  lefthook: ^2.0.12
  tsx: ^4.21.0
  turbo: ^2.7.2
  typescript: ^5.9.3
  vite-tsconfig-paths: ^6.0.3
  vitest: ^4.0.16

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - lefthook
  - msgpackr-extract
  - msw
  - protobufjs
  - sharp
  - unrs-resolver
