import type { ErrorCodeValue } from "@yokg/shared/lib/error-codes";
import { ErrorCode } from "@yokg/shared/lib/error-codes";
import type { BASE_ERROR_CODES } from "better-auth";

export type BetterAuthErrorCode = keyof typeof BASE_ERROR_CODES;

const mapping: Record<BetterAuthErrorCode | "MISSING_OR_NULL_ORIGIN", ErrorCodeValue> = {
  MISSING_OR_NULL_ORIGIN: ErrorCode.INVALID_REQUEST,

  // Sign-in/Authentication errors
  INVALID_EMAIL_OR_PASSWORD: ErrorCode.AUTH.SIGN_IN.INVALID_EMAIL_OR_PASSWORD,
  USER_NOT_FOUND: ErrorCode.AUTH.SIGN_IN.USER_NOT_FOUND,
  INVALID_EMAIL: ErrorCode.AUTH.SIGN_IN.INVALID_EMAIL,
  INVALID_PASSWORD: ErrorCode.AUTH.SIGN_IN.INVALID_PASSWORD,

  // Account/User management errors
  ACCOUNT_NOT_FOUND: ErrorCode.AUTH.ACCOUNT.ACCOUNT_NOT_FOUND,
  CREDENTIAL_ACCOUNT_NOT_FOUND: ErrorCode.AUTH.ACCOUNT.CREDENTIAL_ACCOUNT_NOT_FOUND,
  USER_ALREADY_EXISTS: ErrorCode.AUTH.ACCOUNT.USER_ALREADY_EXISTS,
  USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL:
    ErrorCode.AUTH.ACCOUNT.USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL,
  USER_EMAIL_NOT_FOUND: ErrorCode.AUTH.ACCOUNT.USER_EMAIL_NOT_FOUND,
  FAILED_TO_CREATE_USER: ErrorCode.AUTH.ACCOUNT.FAILED_TO_CREATE_USER,
  FAILED_TO_UPDATE_USER: ErrorCode.AUTH.ACCOUNT.FAILED_TO_UPDATE_USER,
  FAILED_TO_UNLINK_LAST_ACCOUNT: ErrorCode.AUTH.ACCOUNT.FAILED_TO_UNLINK_LAST_ACCOUNT,

  // Session management errors
  SESSION_EXPIRED: ErrorCode.AUTH.SESSION.SESSION_EXPIRED,
  FAILED_TO_CREATE_SESSION: ErrorCode.AUTH.SESSION.FAILED_TO_CREATE_SESSION,
  FAILED_TO_GET_SESSION: ErrorCode.AUTH.SESSION.FAILED_TO_GET_SESSION,

  // Password management errors
  PASSWORD_TOO_SHORT: ErrorCode.AUTH.PASSWORD.PASSWORD_TOO_SHORT,
  PASSWORD_TOO_LONG: ErrorCode.AUTH.PASSWORD.PASSWORD_TOO_LONG,
  USER_ALREADY_HAS_PASSWORD: ErrorCode.AUTH.PASSWORD.USER_ALREADY_HAS_PASSWORD,

  // Email management errors
  EMAIL_NOT_VERIFIED: ErrorCode.AUTH.EMAIL.EMAIL_NOT_VERIFIED,
  EMAIL_CAN_NOT_BE_UPDATED: ErrorCode.AUTH.EMAIL.EMAIL_CAN_NOT_BE_UPDATED,

  // OAuth/Social authentication errors
  PROVIDER_NOT_FOUND: ErrorCode.AUTH.OAUTH.PROVIDER_NOT_FOUND,
  SOCIAL_ACCOUNT_ALREADY_LINKED: ErrorCode.AUTH.OAUTH.SOCIAL_ACCOUNT_ALREADY_LINKED,
  FAILED_TO_GET_USER_INFO: ErrorCode.AUTH.OAUTH.FAILED_TO_GET_USER_INFO,
  ID_TOKEN_NOT_SUPPORTED: ErrorCode.AUTH.OAUTH.ID_TOKEN_NOT_SUPPORTED,

  // Token management errors
  INVALID_TOKEN: ErrorCode.AUTH.TOKEN.INVALID_TOKEN,
};

export function mapBetterAuthError(betterAuthErrorCode: BetterAuthErrorCode): ErrorCodeValue {
  return mapping[betterAuthErrorCode] ?? null;
}
