/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as GraphLayoutRouteImport } from "./routes/graph/layout";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as GraphIndexRouteImport } from "./routes/graph/index";

const GraphLayoutRoute = GraphLayoutRouteImport.update({
  id: "/graph",
  path: "/graph",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => GraphLayoutRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/graph": typeof GraphLayoutRouteWithChildren;
  "/graph/": typeof GraphIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/graph": typeof GraphIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/graph": typeof GraphLayoutRouteWithChildren;
  "/graph/": typeof GraphIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/graph" | "/graph/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/graph";
  id: "__root__" | "/" | "/graph" | "/graph/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  GraphLayoutRoute: typeof GraphLayoutRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/graph": {
      id: "/graph";
      path: "/graph";
      fullPath: "/graph";
      preLoaderRoute: typeof GraphLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/graph/": {
      id: "/graph/";
      path: "/";
      fullPath: "/graph/";
      preLoaderRoute: typeof GraphIndexRouteImport;
      parentRoute: typeof GraphLayoutRoute;
    };
  }
}

interface GraphLayoutRouteChildren {
  GraphIndexRoute: typeof GraphIndexRoute;
}

const GraphLayoutRouteChildren: GraphLayoutRouteChildren = {
  GraphIndexRoute: GraphIndexRoute,
};

const GraphLayoutRouteWithChildren = GraphLayoutRoute._addFileChildren(
  GraphLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphLayoutRoute: GraphLayoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
